name: Deploy E2E Tests Results into GitHub Pages
on:
  workflow_dispatch:
jobs:
  test:
    environment:
      name: e2e
    timeout-minutes: 60
    runs-on: ubuntu-latest
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - name: Print a varible that does not exists
      run: echo $bom_dia
    - name: check the run status
      if: failure()
      run: echo "this job has failed"
    # - uses: actions/upload-artifact@v3
    #   if: always()
    #   with:
    #     name: playwright-report
    #     path: playwright-report/
    #     retention-days: 30
    # - name: Setup Pages
    #   uses: actions/configure-pages@v3
    # - name: Rename index folder to hello
    #   run: mv playwright-report/index.html playwright-report/testing.html
    # - name: Upload artifact
    #   uses: actions/upload-pages-artifact@v2
    #   with:
    #     # Upload entire repository
    #     path: 'playwright-report/'
    # - name: Check list of repo
    #   run: ls
    # - name: Check list of playwright-report
    #   run: ls playwright-report
    # - name: Deploy to GitHub Pages
    #   id: deployment
    #   uses: actions/deploy-pages@v2
    #   with:
    #     token: ${{ secrets.GH_TOKEN }}
    # - name: Deploy to GitHub Pages
    #   uses: crazy-max/ghaction-github-pages@v4
    #   with:
    #     target_branch: gh-pages
    #     build_dir: public
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # - name: Deploy to GitHub Pages
    #   uses: JamesIves/github-pages-deploy-action@3.7.1
    #   with:
    #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    #     BRANCH: main
    #     TARGET_FOLDER: playwright-report/test
    #     FOLDER: 'playwright-report'
    # - name: Deploy to GitHub Pages
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ secrets.GH_TOKEN }}
    #     publish_dir: playwright-report/
    # - name: Create a commit
    #   run: |
    #     git add .github/workflows/playwright-test.yml
    #     git commit -m "Add Playwright test workflow"
    #     git push origin main
