name: final job
on:
  workflow_call:
    inputs:
      job1_status:
        required: true
        type: string
      job2_status:
        required: false
        type: string
      
jobs:
  fail:
    environment:
      name: e2e
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: check the job 1 status
        run: echo "job2 - ${{ inputs.job1_status }}"
      - name: check the job 2 status
        run: echo "job2 - ${{ inputs.job2_status }}"