name: final job
on:
  workflow_call:
    inputs:
      job1_status:
        required: true
        type: boolean
      job2_status:
        required: false
        type: boolean
      
jobs:
  fail:
    environment:
      name: e2e
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: check the job 1 status
        run: gh run view job1
      - name: check the job 2 status
        run: gh run view job2