name: final job
on:
  workflow_call:
jobs:
  fail:
    environment:
      name: e2e
    runs-on: ubuntu-latest
    steps:
      - name: check the job 1 status
        run: echo "job1 status - ${{ needs.job1.status }}"
      - name: check the job 2 status
        run: echo "job2 status - ${{ needs.job2.status }}"