name: Fail job1
on:
  workflow_call:
    outputs:
      job1_status: ${{ steps.checkStep.outputs.job1_status }}
jobs:
  fail:
    environment:
      name: e2e
    runs-on: ubuntu-latest
    steps:
      - name: force fail
        run: exit 1
      - name: check the run status
        if: failure()
        run: echo "job1_status=failed" >> "$GITHUB_OUTPUT"