name: Fail job1
on:
  workflow_call:
jobs:
  fail:
    environment:
      name: e2e
    runs-on: ubuntu-latest
    steps:
      - name: force fail
        run: exit 1
      - name: check the run status
        if: failure()
        run: echo "this job has failed"